"use client";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, Coffee, Flower2, Plus, Minus, Sun } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { breakfast, foods, moreLunch, phone } from "../cafe-data";
export default function MenuPage() {
  const [meal,setMeal]=useState("breakfast");const [expanded,setExpanded]=useState<number|null>(null);const [showMore,setShowMore]=useState(false);
  return <main id="main" className="menu-page"><section className="page-intro container"><Coffee className="intro-icon" size={42} strokeWidth={1.2}/><p className="eyebrow">Made for your everyday</p><h1>A little something<br/><em>to love.</em></h1><p>From your first coffee to your lunch break.<br/>Find the good thing your day is missing.</p></section>
    <section className="menu-area container" aria-label="Breakfast and lunch menu"><Tabs value={meal} onValueChange={setMeal}><TabsList className="meal-tabs" aria-label="Choose breakfast or lunch"><TabsTrigger className="meal-tab" value="breakfast"><Coffee size={18}/>Breakfast<span>7:30–11 AM</span></TabsTrigger><TabsTrigger className="meal-tab" value="lunch"><Sun size={18}/>Lunch<span>11 AM–2:30 PM</span></TabsTrigger></TabsList>
      <TabsContent value="breakfast"><div className="breakfast-menu"><div className="breakfast-welcome"><div className="breakfast-photo"><img src="/images/breakfast-croissant.webp" alt="Café 21 sausage, egg and cheese croissant" width="1200" height="1600" loading="lazy"/></div><h2>Good morning,<br/><em>lovely.</em></h2><p>A warm cup. Your favorite breakfast.<br/>A gentler start to the day.</p><span className="handwritten">a little morning ritual</span></div><div className="breakfast-list">{breakfast.map(([name,desc,price])=><div className="breakfast-item" key={name}><div><h3>{name}</h3><p>{desc}</p></div><strong>${price}</strong></div>)}</div></div><div className="breakfast-photo-row">{[["breakfast-bagel.webp","A lovely breakfast bagel","Café 21 ham, scrambled egg and cheese bagel"],["veggie-burrito.webp","A little breakfast burrito","Café 21 veggie breakfast burrito"],["ham-panini.webp","Something warm & toasty","Café 21 toasted ham panini"]].map(([image,caption,alt])=><figure key={image}><img src={`/images/${image}`} alt={alt} width="1200" height="900" loading="lazy"/><figcaption>{caption}</figcaption></figure>)}</div><div className="menu-bottom"><span>Breakfast served 7:30–11 AM</span><a className="text-link" href="https://www.cafe21express.com/menu-breakfast-2/" target="_blank" rel="noreferrer">Full breakfast menu <ArrowUpRight size={17}/></a></div></TabsContent>
      <TabsContent value="lunch"><div className="lunch-heading"><h2>Lunch, with a little <em>love.</em></h2><p>Your usual, or something new?</p></div><div className="food-grid">{foods.map((food,i)=><article className="food-card" key={food.name}><button className="food-image-wrap" aria-label={`Explore ${food.name}`} aria-expanded={expanded===i} onClick={()=>setExpanded(expanded===i?null:i)}><img src={`/images/${food.image}`} alt={food.alt} width="614" height="621" loading="lazy"/><span className="food-price">${food.price}</span><span className="food-peek">Take a little peek <ArrowRight size={18}/></span></button><div className="food-copy"><div className="food-name-row"><h3>{food.name}</h3><button className="food-expand" aria-label={`${expanded===i?"Hide":"Show"} ${food.name} details`} aria-expanded={expanded===i} aria-controls={`food-${i}`} onClick={()=>setExpanded(expanded===i?null:i)}>{expanded===i?<Minus size={19}/>:<Plus size={19}/>}</button></div>{expanded===i&&<div className="food-description" id={`food-${i}`}><p>{food.description}</p><a className="text-link" href={phone}>Call to order <ArrowRight size={16}/></a></div>}</div></article>)}</div>{showMore&&<div className="more-menu" id="more-lunch">{moreLunch.map(([name,price])=><div key={name}><span>{name}</span><strong>${price}</strong></div>)}</div>}<div className="menu-bottom"><button className="text-link" aria-expanded={showMore} aria-controls="more-lunch" onClick={()=>setShowMore(!showMore)}>{showMore?"A little less menu":"More to love on the menu"}{showMore?<Minus size={18}/>:<Plus size={18}/>}</button><a className="text-link" href="https://www.cafe21express.com/menu-lunch/" target="_blank" rel="noreferrer">Full lunch menu <ArrowUpRight size={17}/></a></div></TabsContent>
    </Tabs><p className="price-note">Prices shown from our published menu. Availability and prices may change.</p></section><div className="small-invitation container"><Flower2 size={30} strokeWidth={1.2}/><p>Found your favorite? <a href={phone}>Give us a ring.</a></p></div></main>;
}
