"use client";
import { useState } from "react";
import { ArrowUpRight, Plus, Minus } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { breakfast, foods, moreLunch, phone } from "../cafe-data";
import { PageHeading } from "../editorial";
export default function MenuPage(){
 const [meal,setMeal]=useState("breakfast");const [expanded,setExpanded]=useState<number|null>(null);const [showMore,setShowMore]=useState(false);
 return <main id="main"><PageHeading number="01" label="Breakfast & lunch" title="The" accent="menu." description="Your morning ritual. Your midday escape. Explore the Café 21 favorites."/>
 <section className="menu-area container" aria-label="Breakfast and lunch menu"><Tabs value={meal} onValueChange={setMeal}><TabsList className="meal-tabs" aria-label="Choose breakfast or lunch"><TabsTrigger className="meal-tab" value="breakfast">Breakfast<span>7:30–11 AM</span></TabsTrigger><TabsTrigger className="meal-tab" value="lunch">Lunch<span>11 AM–2:30 PM</span></TabsTrigger></TabsList>
 <TabsContent value="breakfast"><div className="breakfast-menu"><figure className="breakfast-welcome"><img src="/images/breakfast-croissant.webp" alt="Café 21 sausage, egg and cheese croissant" width="1200" height="1600"/><figcaption><span>Start here</span><h2>Morning<br/><em>rituals.</em></h2></figcaption></figure><div className="breakfast-list">{breakfast.map(([name,desc,price])=><div className="breakfast-item" key={name}><div><h3>{name}</h3><p>{desc}</p></div><strong>${price}</strong></div>)}</div></div><div className="breakfast-photo-row">{[["breakfast-bagel.webp","Ham, egg & cheese bagel","Café 21 ham, scrambled egg and cheese bagel"],["veggie-burrito.webp","Veggie breakfast burrito","Café 21 veggie breakfast burrito"],["ham-panini.webp","Toasted ham panini","Café 21 toasted ham panini"]].map(([image,caption,alt],i)=><figure key={image}><img src={`/images/${image}`} alt={alt} width="1200" height="900" loading="lazy"/><figcaption><span>0{i+1}</span>{caption}</figcaption></figure>)}</div><div className="menu-bottom"><span>Breakfast served 7:30–11 AM</span><a className="text-link" href="https://www.cafe21express.com/menu-breakfast-2/" target="_blank" rel="noreferrer">Full breakfast menu <ArrowUpRight size={18}/></a></div></TabsContent>
 <TabsContent value="lunch"><div className="lunch-heading"><h2>The midday <em>selection.</em></h2><p>Your usual, or something new.</p></div><div className="food-grid">{foods.map((food,i)=><article className="food-card" key={food.name}><button className="food-image-wrap" aria-label={`Explore ${food.name}`} aria-expanded={expanded===i} onClick={()=>setExpanded(expanded===i?null:i)}><img src={`/images/${food.image}`} alt={food.alt} width="614" height="621" loading="lazy"/><span className="food-price">${food.price}</span><span className="food-peek">View details <ArrowUpRight size={20}/></span></button><div className="food-copy"><div className="food-name-row"><h3>{food.name}</h3><button className="food-expand" aria-label={`${expanded===i?"Hide":"Show"} ${food.name} details`} aria-expanded={expanded===i} aria-controls={`food-${i}`} onClick={()=>setExpanded(expanded===i?null:i)}>{expanded===i?<Minus size={19}/>:<Plus size={19}/>}</button></div>{expanded===i&&<div className="food-description" id={`food-${i}`}><p>{food.description}</p><a className="text-link" href={phone}>Call to order <ArrowUpRight size={16}/></a></div>}</div></article>)}</div>{showMore&&<div className="more-menu" id="more-lunch">{moreLunch.map(([name,price])=><div key={name}><span>{name}</span><strong>${price}</strong></div>)}</div>}<div className="menu-bottom"><button className="text-link" aria-expanded={showMore} aria-controls="more-lunch" onClick={()=>setShowMore(!showMore)}>{showMore?"Show less":"More from the lunch menu"}{showMore?<Minus size={18}/>:<Plus size={18}/>}</button><a className="text-link" href="https://www.cafe21express.com/menu-lunch/" target="_blank" rel="noreferrer">Full lunch menu <ArrowUpRight size={18}/></a></div></TabsContent>
 </Tabs><p className="price-note">Prices shown from our published menu. Availability and prices may change.</p></section><section className="menu-callout container"><h2>Found your <em>favorite?</em></h2><a className="text-link" href={phone}>Call Café 21 <ArrowUpRight size={20}/></a></section></main>;
}
