"use client";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { ArrowUpRight, Menu, X } from "lucide-react";
import { phone } from "./cafe-data";
const links = [["/", "Home"], ["/menu", "The menu"], ["/our-place", "Our place"], ["/catering", "Catering"], ["/visit", "Visit us"]];
export function CafeHeader() {
  const path=usePathname();const [open,setOpen]=useState(false);
  useEffect(()=>setOpen(false),[path]);
  useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false);};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close);},[open]);
  return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="masthead container"><p className="masthead-location">Denver, Colorado<br/><span>Since 1997</span></p><a href="/" className="wordmark" aria-label="Cafe 21 Express home">café<span>21</span><small>EXPRESS</small></a><a className="masthead-contact" href={phone}>303-297-3651<ArrowUpRight size={15}/></a><button className="nav-toggle" aria-label={open?"Close navigation":"Open navigation"} aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div><nav className="desktop-nav container" aria-label="Main navigation">{links.map(([href,label])=><a key={href} href={href} aria-current={path===href?"page":undefined}>{label}</a>)}</nav>{open&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Mobile navigation">{links.map(([href,label],i)=><a key={href} href={href} aria-current={path===href?"page":undefined} onClick={()=>setOpen(false)}><span>0{i+1}</span>{label}<ArrowUpRight size={20}/></a>)}</nav>}</header></>;
}
export function CafeFooter(){return <footer className="site-footer"><div className="container"><div className="footer-top"><h2>See you <em>downtown.</em></h2><a className="text-link" href="/visit">Find Café 21 <ArrowUpRight size={21}/></a></div><div className="footer-links"><nav aria-label="Footer navigation">{links.map(([href,label])=><a key={href} href={href}>{label}</a>)}</nav><div><span className="footer-label">The address</span><p>999 18th St, Suite 101<br/>Denver, CO 80202</p><a href={phone}>303-297-3651</a></div><div><span className="footer-label">The everyday</span><p>Breakfast · 7:30–11 AM<br/>Lunch · 11 AM–2:30 PM</p><a href="https://www.facebook.com/people/Cafe-21-Express/61560865275557/" target="_blank" rel="noreferrer">Facebook <ArrowUpRight size={14}/></a></div></div><a className="footer-signature" href="/" aria-label="Cafe 21 Express home">café21</a><div className="footer-bottom"><span>© {new Date().getFullYear()} Café 21 Express</span><span>Downtown Denver. Since 1997.</span></div></div></footer>;}
