import { ArrowRight, ArrowUpRight } from "lucide-react";
import { FavoriteCarousel } from "./wow";
export default function Home(){return <main id="main">
  <section className="editorial-cover container" aria-labelledby="hero-title"><div className="edition-line"><span>Breakfast. Lunch. A moment in the city.</span><span>Café 21 Express / Denver</span></div><h1 id="hero-title">A taste of <em>downtown.</em></h1><div className="cover-spread"><figure className="cover-photo"><img src="/images/Green-room-seating-with-couches.webp" alt="The living green wall and seating in the Green room at Denver Place" width="900" height="1200" fetchPriority="high"/><figcaption>The Green room at Denver Place</figcaption></figure><aside className="cover-rail"><span className="rail-label">Your daily destination</span><h2>Good taste.<br/><em>Every day.</em></h2><div className="rail-hours"><div><span>Breakfast</span><strong>7:30–11 AM</strong></div><div><span>Lunch</span><strong>11 AM–2:30 PM</strong></div></div><a href="/menu">Discover the menu <ArrowUpRight size={24}/></a></aside></div><div className="cover-footnote"><span>999 18th Street · Inside Denver Place</span><a href="/visit">Make your way here <ArrowUpRight size={15}/></a></div></section>
  <section className="editorial-intro container"><p className="eyebrow">01 / The everyday, considered</p><h2>A morning ritual.<br/>A midday escape.<br/><em>Always, Café 21.</em></h2><div><p>Coffee, breakfast, and lunch in the heart of downtown Denver. Familiar favorites, a place to pause, and a different pace for your day.</p><a className="text-link" href="/our-place">Our place in the city <ArrowUpRight size={18}/></a></div></section>
  <section className="menu-edit container" id="menu"><div className="section-heading"><div><p className="eyebrow">02 / From the kitchen</p><h2>The daily <em>edit.</em></h2></div><a className="text-link" href="/menu">Explore the full menu <ArrowUpRight size={18}/></a></div><FavoriteCarousel/></section>
  <section className="space-edit container" id="our-place"><figure className="space-main"><img src="/images/Outside-seating-of-round-table-and-seats.webp" alt="Sculptural wood booths and seating at Denver Place" width="900" height="1200" loading="lazy"/><figcaption>Denver Place / A seat in the city</figcaption></figure><div className="space-copy"><p className="eyebrow">03 / A change of scene</p><h2>A different<br/><em>pace.</em></h2><p>Step out of your routine. Pick up your favorite from Café 21, settle into the Green room, and let the city carry on for a moment.</p><a className="text-link" href="/our-place">Step inside <ArrowUpRight size={18}/></a><figure className="space-detail"><img src="/images/tables-and-seats-2-condensed-2.webp" alt="The open Green room seating area at Denver Place" width="900" height="1200" loading="lazy"/><figcaption>Room to take a moment.</figcaption></figure></div></section>
  <section className="table-edit" id="catering"><div className="container table-grid"><div><p className="eyebrow">04 / Good company</p><h2>For the<br/><em>table.</em></h2><p>Team lunches. Celebrations. The pleasure of sharing something good.</p><a className="text-link" href="/catering">Discover catering <ArrowUpRight size={20}/></a></div><figure><img src="/images/blt.webp" alt="Café 21 BLT sandwiches with fresh greens" width="1600" height="900" loading="lazy"/><figcaption>Bring Café 21 to your next gathering.</figcaption></figure></div></section>
  <section className="location-line container" id="visit"><div><p className="eyebrow">A downtown address, since 1997</p><h2>Your next <em>stop.</em></h2></div><div><p>999 18th Street, Suite 101<br/>Denver Place · North Tower · Ground floor</p><a className="text-link" href="/visit">Plan your visit <ArrowRight size={19}/></a></div></section>
</main>;}
