import { ArrowRight, Coffee, Flower2, Heart, MapPin, Sun } from "lucide-react";
import { FavoriteCarousel } from "./wow";
export default function Home() {return <main id="main">
  <section className="home-hero container" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span/>Your downtown little escape</p><h1 id="hero-title">Your little<br/>downtown<br/><em>happy place.</em></h1><p className="hero-description">Coffee, a lovely bite, and a moment to yourself.<br className="desktop-break"/> Come find your everyday favorite at Café 21.</p><div className="hero-actions"><a href="/menu" className="button">Explore the menu <ArrowRight size={18}/></a><a href="/visit" className="text-link">Come say hello <Heart size={17}/></a></div><p className="hero-address"><MapPin size={15}/>Tucked inside Denver Place · Since 1997</p></div><div className="hero-collage"><div className="hero-arch"><img src="/images/Green-room-seating-with-couches.webp" alt="Leafy green walls and inviting seating in the Green room at Denver Place" width="900" height="1200" fetchPriority="high"/><div className="arch-caption"><MapPin size={14}/>The Green room at Denver Place</div></div><div className="coffee-seal"><span>A LITTLE PAUSE</span><Coffee size={48} strokeWidth={1.1}/><em>just for you</em></div><div className="mini-postcard"><img src="/images/croissant-sandwich.webp" alt="Café 21's golden croissant sandwich" width="608" height="611"/><span>lunch date? <Heart size={15}/></span></div><Flower2 className="hero-flower" size={69} strokeWidth={1.1} aria-hidden="true"/><span className="handwritten hero-handwritten">stay a little while</span></div></section>
  <div className="day-ribbon"><div className="container"><span><Coffee size={21} strokeWidth={1.4}/>Morning coffee</span><Flower2 size={19} aria-hidden="true"/><span><Sun size={21} strokeWidth={1.4}/>Breakfast & lunch</span><Flower2 size={19} aria-hidden="true"/><span><Heart size={21} strokeWidth={1.4}/>A little time for you</span></div></div>
  <section className="favorites-section container" id="menu"><div className="section-heading"><div><p className="eyebrow">From our little kitchen</p><h2>Good food.<br/><em>Lovely little moments.</em></h2></div><a className="text-link" href="/menu">All the good things <ArrowRight size={18}/></a></div><FavoriteCarousel/></section>
  <section className="home-place" id="our-place"><div className="container story-grid"><div className="story-photo"><img src="/images/Outside-seating-of-round-table-and-seats.webp" width="900" height="1200" alt="Cozy circular seating areas at Denver Place" loading="lazy"/><span className="photo-note">a seat with your name on it ♡</span></div><div className="story-copy"><Flower2 size={42} strokeWidth={1.2} aria-hidden="true"/><p className="eyebrow">A good place to land</p><h2>A bite to eat.<br/>A breath of <em>fresh air.</em></h2><p>Step away from the busy for a bit. Pick up your favorite from Café 21, then settle into the Green room at Denver Place.</p><p>We’ve been part of downtown Denver since 1997. We’d love to be part of your day, too.</p><a className="button button-outline" href="/our-place">Get to know our corner <ArrowRight size={18}/></a></div></div></section>
  <section className="home-catering container" id="catering"><div className="catering-note-card"><Heart size={31} strokeWidth={1.3}/><p className="eyebrow">For your favorite people</p><h2>Good things are<br/>better <em>shared.</em></h2><p>Team lunches, little celebrations, and all the moments in between. Let’s bring something lovely to your table.</p><a className="button" href="/catering">A little more about catering <ArrowRight size={18}/></a></div><div className="catering-table"><img src="/images/Club-Combo-2.webp" alt="Café 21 club sandwiches" width="576" height="299" loading="lazy"/><span className="handwritten">save a bite for me ♡</span></div></section>
  <section className="visit-invite container" id="visit"><div><p className="eyebrow">Come on over</p><h2>We’ll be right <em>here.</em></h2><p>999 18th Street, Suite 101 · Denver Place</p></div><a href="/visit" className="button button-outline">Plan your little visit <ArrowRight size={18}/></a></section>
</main>;}
